### ISSUE TITLE
curl_easy.h:137:29: error: 'CURLINFO_TLS_SESSION' was not declared in this scope

### ISSUE THREAD

**Issue by xxxxn** [JosephP91/curlcpp#98]
Curlcpp fails to build on latest Centos 7 with the following error:
```
[  7%] Building CXX object src/CMakeFiles/curlcpp.dir/curl_easy.cpp.o
In file included from /root/curlcpp/src/curl_easy.cpp:6:0:
/root/curlcpp/include/curl_easy.h:137:29: error: 'CURLINFO_TLS_SESSION' was not declared in this scope
         CURLCPP_DEFINE_INFO(CURLINFO_TLS_SESSION,struct curl_tlssessioninfo *);
                             ^
/root/curlcpp/include/curl_easy.h:46:31: note: in definition of macro 'CURLCPP_DEFINE_INFO'
     template <> struct info_t<info> {\
                               ^
/root/curlcpp/include/curl_easy.h:46:35: error: template argument 1 is invalid
     template <> struct info_t<info> {\
                                   ^
/root/curlcpp/include/curl_easy.h:137:9: note: in expansion of macro 'CURLCPP_DEFINE_INFO'
         CURLCPP_DEFINE_INFO(CURLINFO_TLS_SESSION,struct curl_tlssessioninfo *);
         ^
make[2]: *** [src/CMakeFiles/curlcpp.dir/curl_easy.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/curlcpp.dir/all] Error 2
make: *** [all] Error 2
```
This is strange considering that according to documantation acceptable version of curl should be  >=7.28.

But, according to this page: https://curl.haxx.se/libcurl/c/CURLINFO_TLS_SESSION.html
The CURLINFO_TLS_SESSION was added in 7.34

**Comment by xxxxn** [comment]
Build with 7.52 version of libcurl is successful.

**Comment by JosephP91** [comment]
Hi @xxxxn maybe it was only added in 7.34 but not fully supported?

**Comment by xxxxn** [comment]
Well I meant that you probably should correct readme and shift the oldest supported version up to 7.34 from 7.28)

**Comment by JosephP91** [comment]
Done! Thank you for pointing it out!

**Comment by RonnieHu** [comment]
> Done! Thank you for pointing it out!

Bro, your cmakelists.txt(v2.1) didn't update the curl version, it is still set(CURL_MIN_VERSION "7.28.0")

**Comment by JosephP91** [comment]
@RonnieHu oops, sorry. Now should be ok. I've published a new version (3.0)
